'use strict';
(() => {
const BOOKS=['Death & Co','Tropical Standard','Essential Cocktail Book','Essential Cocktails 2021','Agave Companion'];
const PHOTO_VERSION='2026-08-17-quality-v3';
if(localStorage.getItem('shakerrr_photo_cache_version')!==PHOTO_VERSION){state.remotePhotos={};localStorage.removeItem('shakerrr_remote_photos');localStorage.setItem('shakerrr_photo_cache_version',PHOTO_VERSION)}

// The old loader reads a private development HTML file and can silently add old records
// after the clean database is already on screen. It is intentionally disabled in production.
loadLegacyLibrary=async function(){};

function srcName(r){return r.baseSource||(r.collections||[]).find(c=>!['MJ / Shakerrr','Shakerrr'].includes(c))||'Shakerrr'}
function visibleVersions(r){return (r.versions||[]).filter(v=>v.usable!==false)}
function versionCount(r){const s=new Set(visibleVersions(r).map(v=>v.label||v.key||'Source'));if(r.baseSource)s.add(r.baseSource);return Math.max(1,s.size)}
function garnishHtml(g=''){return g?`<div class="garnish-box"><b>Garnish</b>${esc(g)}</div>`:''}
function validBookVersion(r,b){return (r.versions||[]).find(v=>v.label===b&&v.usable!==false)}
function normDrink(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function dbIngredients(d){const a=[];for(let i=1;i<=15;i++){const n=String(d['strIngredient'+i]||'').trim();if(n)a.push({name:n,amount:String(d['strMeasure'+i]||'').trim()})}return a}
function inferMethod(s=''){if(/shake/i.test(s))return'Shake';if(/stir/i.test(s))return'Stir';if(/blend/i.test(s))return'Blend';if(/build|pour.*glass/i.test(s))return'Build';return'Recipe'}
async function enrichRecipe(r){if(!r||r.quality!=='limited'||r._externalTried)return r;r._externalTried=true;try{const res=await fetch(`https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${encodeURIComponent(r.name)}`);if(!res.ok)return r;const j=await res.json(),key=normDrink(r.name),d=(j.drinks||[]).find(x=>normDrink(x.strDrink)===key);if(!d)return r;const ing=dbIngredients(d);if(ing.length<2)return r;const url=`https://www.thecocktaildb.com/drink/${d.idDrink}`;r.ingredients=ing;r.instructions=String(d.strInstructions||'').trim();r.note='';r.method=inferMethod(r.instructions);if(r.family==='Other')r.family=d.strCategory||'Cocktail';r.image=d.strDrinkThumb||null;r.baseSource='TheCocktailDB';r.quality='external';r.versions=[{label:'TheCocktailDB',key:'cocktaildb-'+d.idDrink,type:'reference',usable:true,url,ingredients:ing,instructions:r.instructions,note:''},...visibleVersions(r).filter(v=>v.label!=='TheCocktailDB')];if(d.strDrinkThumb){state.remotePhotos[r.id]={url:d.strDrinkThumb,credit:'TheCocktailDB',link:url};saveRemotePhotos()}}catch(e){console.warn('Recipe source lookup failed',e)}return r}

openRecipe=async function(id){if(!state.byId.has(id))return;if(state.page!=='detail')state.prevPage=state.page;state.current=id;state.page='detail';closeSearch();scrollTo({top:0,behavior:'smooth'});const r=state.byId.get(id);if(r.quality==='limited'&&!r._externalTried){$('#main').innerHTML='<section class="page"><div class="shell"><div class="empty">Checking the recipe source...</div></div></section>';await enrichRecipe(r)}renderDetail(id)};

card=function(r){const vc=versionCount(r),line=r.quality==='limited'?'Open to verify against an exact external match':(r.ingredients||[]).slice(0,5).map(i=>i.name).join(' · ');return `<article class="card" role="button" tabindex="0" data-recipe="${r.id}"><div class="card-photo"><span class="photo-status">Photo loading...</span><img data-photo-id="${r.id}" alt="${attr(r.name)}"><span class="badge">${esc(r.category)}</span><button class="heart" data-action="fav" data-id="${r.id}" aria-label="Favourite">${state.favs.has(r.id)?'♥':'♡'}</button></div><div class="card-body"><div class="origin">${esc(r.country||srcName(r))}</div><h3>${esc(r.name)}</h3><div class="ingredient-line">${esc(line)}</div><div class="tags"><span class="tag gold">${esc(r.method||'Recipe')}</span>${r.family?`<span class="tag blue">${esc(r.family)}</span>`:''}${vc>1?`<span class="tag">${vc} versions</span>`:''}</div></div></article>`};

allVersions=function(r){const out=[],seen=new Set(),baseSig=JSON.stringify((r.ingredients||[]).map(i=>[i.amount||'',i.name||'']));const source=visibleVersions(r);const baseDuplicate=source.some(v=>JSON.stringify((v.ingredients||[]).map(i=>[i.amount||'',i.name||'']))===baseSig);if(!baseDuplicate)out.push({label:srcName(r)==='Shakerrr'?'Shakerrr':srcName(r),key:'base',ingredients:r.ingredients,instructions:r.instructions,note:r.note,garnish:r.garnish});for(const v of source){const k=(v.label||'')+'|'+JSON.stringify((v.ingredients||[]).map(i=>[i.amount||'',i.name||'']));if(seen.has(k))continue;seen.add(k);out.push(v)}const my=localStorage.getItem('shakerrr_my_'+r.id);out.push({label:'My Recipe',key:'mine',mine:true,text:my||''});const socials=JSON.parse(localStorage.getItem('shakerrr_social_'+r.id)||'[]');socials.forEach((s,i)=>out.push({...s,label:`${s.platform||'Social'} · ${s.creator||'saved'}`,key:'social'+i,social:true}));out.push({label:'+ Social recipe',key:'addsocial',addsocial:true});return out};

renderVersions=function(r){const vs=allVersions(r),m=$('#versionMount');m.innerHTML=`<div class="version-tabs">${vs.map((v,i)=>`<button class="version-tab ${i===0?'active':''}" data-version="${i}">${esc(v.label)}</button>`).join('')}</div><div id="versionPane"></div>`;renderVersion(0)};
renderVersion=function(i){const r=state.byId.get(state.current),vs=allVersions(r),v=vs[i];if(!v)return;$$('.version-tab').forEach((b,j)=>b.classList.toggle('active',j===i));const pane=$('#versionPane');if(v.mine){pane.innerHTML=`<div class="version-pane"><div class="source-head"><b>My Recipe</b><span>saved on this device</span></div><textarea id="myRecipeText" placeholder="Write your own recipe, method, garnish, notes...">${esc(v.text)}</textarea><button class="mini-btn" data-action="save-my-recipe">Save my recipe</button></div>`;return}if(v.addsocial){pane.innerHTML=`<div class="version-pane"><div class="source-head"><b>Add social recipe</b><span>Instagram / TikTok / bar post</span></div><div class="form-grid"><div class="field"><label>Platform</label><input id="socialPlatform" class="form-control" placeholder="Instagram"></div><div class="field"><label>Creator</label><input id="socialCreator" class="form-control" placeholder="@creator"></div><div class="field full"><label>Original link</label><input id="socialUrl" class="form-control" placeholder="https://..."></div><div class="field full"><label>Recipe + method</label><textarea id="socialRecipe" class="form-control" placeholder="Ingredients, amounts, method..."></textarea></div><div class="field full"><label>Photo</label><input id="socialPhoto" class="form-control" type="file" accept="image/*"></div></div><button class="mini-btn" data-action="save-social">Save social version</button></div>`;return}const ing=(v.ingredients||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(displayAmt(x.amount))}</td></tr>`).join('');pane.innerHTML=`<div class="version-pane">${v.photo?`<img class="version-photo" src="${attr(v.photo)}" alt="Recipe photo">`:''}<div class="source-head"><b>${esc(v.label)}</b>${v.url?`<a href="${attr(v.url)}" target="_blank" rel="noopener">Source ↗</a>`:'<span>compare in place</span>'}</div><table class="ingredient-table">${ing}</table>${v.instructions?`<div class="method-box"><b>Method</b>${esc(v.instructions)}</div>`:''}${garnishHtml(v.garnish||'')}${v.note?`<div class="note-box"><b>Notes</b>${esc(v.note)}</div>`:''}${v.social&&v.url?`<a class="mini-btn" href="${attr(v.url)}" target="_blank" rel="noopener">Open original post ↗</a>`:''}</div>`};

renderDetail=function(id){const r=state.byId.get(id);if(!r)return;state.current=id;const ingredients=(r.ingredients||[]).map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(displayAmt(i.amount))}</td></tr>`).join('');$('#main').innerHTML=`<section class="page"><div class="shell"><button class="back" data-nav="${state.prevPage||'cocktails'}">← Back</button><div class="detail"><div class="detail-photo"><span class="photo-status">Photo loading...</span><img data-photo-id="${id}" alt="${attr(r.name)}"><div class="photo-credit"></div><div class="photo-controls"><button data-action="upload-photo" data-id="${id}">Upload my photo</button><button data-action="use-system-photo" data-id="${id}">Use system photo</button><button data-action="use-my-photo" data-id="${id}">Use my photo</button><button data-action="remove-my-photo" data-id="${id}">Remove my photo</button><button data-action="refresh-photo" data-id="${id}">Find another</button></div></div><div class="detail-copy"><div class="eyebrow"><span>${esc(r.country||'Shakerrr')}</span><span>•</span><span>${esc(r.category)}</span><span>•</span><span>${esc(r.family||'Cocktail')}</span></div><h1>${esc(r.name)}</h1>${r.note?`<div class="detail-note">${esc(r.note)}</div>`:''}<div class="facts"><div class="fact"><small>Method</small><b>${esc(r.method||'Recipe')}</b></div><div class="fact"><small>Family</small><b>${esc(r.family||'Cocktail')}</b></div><div class="fact"><small>Versions</small><b>${versionCount(r)}</b></div><div class="fact"><small>Source</small><b>${esc(srcName(r))}</b></div></div><div class="spec-title"><h3>Recipe</h3><span>MJ</span></div><table class="ingredient-table">${ingredients}</table>${r.instructions?`<div class="method-box"><b>Method</b>${esc(r.instructions)}</div>`:''}${garnishHtml(r.garnish||'')}${r.substitutions?`<div class="sub-box"><b>Substitutions</b>${esc(r.substitutions)}</div>`:''}${r.note?`<div class="note-box"><b>Notes</b>${esc(r.note)}</div>`:''}<div class="version-section"><h2>Recipe versions</h2><div id="versionMount"></div></div></div></div></div></section>`;hydratePhotos();renderVersions(r)};

renderBooks=function(){const groups={};BOOKS.forEach(b=>groups[b]=[]);state.recipes.forEach(r=>BOOKS.forEach(b=>{if(validBookVersion(r,b))groups[b].push(r)}));BOOKS.forEach(b=>groups[b].sort((a,b)=>a.name.localeCompare(b.name)));if(state.book&&groups[state.book]){const a=groups[state.book];$('#main').innerHTML=`<section class="page"><div class="shell"><button class="back" data-action="book-back">← All books</button><div class="toolbar"><div><h1>${esc(state.book)}</h1><p class="subtitle">Cocktail recipes only. Incomplete OCR rows are hidden instead of being presented as drinks.</p></div></div><div class="countline">${a.length} screened recipes</div><div class="cards book-recipe-grid">${a.map(card).join('')}</div></div></section>`;hydratePhotos();return}state.book=null;$('#main').innerHTML=`<section class="page"><div class="shell"><div class="toolbar"><div><h1>Books</h1><p class="subtitle">Choose a book, then browse actual cocktail recipes from that source.</p></div></div><div class="book-shelf-grid">${BOOKS.map((b,i)=>`<button class="book-shelf" data-book="${encodeURIComponent(b)}"><span class="book-no">0${i+1}</span><span class="book-copy"><small>${groups[b].length} screened recipes</small><h3>${esc(b)}</h3><p>${esc(BOOK_DESCRIPTIONS[b]||'Cocktail recipes')}</p></span><span class="book-arrow">→</span></button>`).join('')}</div></div></section>`};
renderMovies=function(){const rows=state.recipes.map(r=>({r,v:(r.versions||[]).find(v=>v.label==='Cocktails from Movies'&&v.usable!==false)})).filter(x=>x.v).sort((a,b)=>a.r.name.localeCompare(b.r.name));$('#main').innerHTML=`<section class="page"><div class="shell"><div class="toolbar"><div><h1>Cocktails from Movies</h1><p class="subtitle">Film-linked cocktail recipes with complete enough specs to use.</p></div></div><div class="countline">${rows.length} screened movie cocktails</div><div class="movies-grid">${rows.map(({r,v})=>`<button class="movie-card" data-recipe="${r.id}"><div class="card-photo"><span class="photo-status">Photo loading...</span><img data-photo-id="${r.id}" alt="${attr(r.name)}"></div><div class="movie-meta"><small>${esc([r.movie?.film,r.movie?.year].filter(Boolean).join(' · ')||'Cinema')}</small><h3>${esc(r.name)}</h3><p>${esc((v.ingredients||[]).slice(0,5).map(i=>i.name).join(' · '))}</p></div></button>`).join('')}</div></div></section>`;hydratePhotos()};
renderDiscover=function(){const featured=['Negroni','Jungle Bird','Padang Swizzle','Rhythm and Soul','Bitter Tom','Naked And Famous','Paper Plane','Donn’s Demon'].map(n=>state.recipes.find(r=>r.name.toLowerCase()===n.toLowerCase())).filter(Boolean),hero=featured[0]||state.recipes[0];$('#main').innerHTML=`<section class="page"><div class="shell"><div class="hero"><div class="hero-media"><span class="photo-status">Photo loading...</span><img data-photo-id="${hero.id}" alt="${attr(hero.name)}"></div><div class="hero-copy"><div class="kicker">MJ Cocktail Reference</div><h1>Recipes, versions, bottles and the relationships between drinks.</h1><p>${state.recipes.length} cleaned cocktail records are searchable in one place. Book shelves and movie collections show only screened recipe entries.</p><div class="btnrow"><button class="primary" data-nav="cocktails">Browse recipes</button><button class="secondary" data-action="surprise">Surprise me</button><button class="secondary" data-nav="families">Open family graph</button></div><div class="hero-stats"><div><b>${state.recipes.length}</b><small>recipes</small></div><div><b>${recipeCountByCountry().size}</b><small>countries</small></div><div><b>${BOOKS.length}</b><small>book sources</small></div></div></div></div><div class="section-head"><div><h2>MJ shelf</h2><p>Classics and obscure drinks together.</p></div><button class="text-link" data-nav="cocktails">All recipes ↗</button></div><div class="cards">${featured.map(card).join('')}</div></div></section>`;hydratePhotos()};

let q=[],active=0,observer=null;const MAX=4;
function schedule(img){if(!img||img.dataset.photoQueued)return;img.dataset.photoQueued='1';q.push(img);pump()}
function pump(){while(active<MAX&&q.length){const img=q.shift();if(!img?.isConnected)continue;active++;Promise.resolve(loadPhoto(img.dataset.photoId,img)).catch(()=>{}).finally(()=>{active--;pump()})}}
hydratePhotos=function(root=$('#main')){if(!root)return;if(!observer&&'IntersectionObserver'in window)observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){observer.unobserve(e.target);schedule(e.target)}}),{rootMargin:'700px'});$$('img[data-photo-id]:not([data-photo-wired])',root).forEach((img,i)=>{img.dataset.photoWired='1';img.loading='lazy';if(img.closest('.detail-photo,.hero-media')||i<6||!observer)schedule(img);else observer.observe(img)})};
function photoKey(r){return normDrink(r.name).split(' ').filter(x=>x.length>2&&!['the','and','with','old','new'].includes(x))}
function photoScore(r,x){const t=[x.title,x.description,(x.tags||[]).map?.(z=>z.name).join(' ')].filter(Boolean).join(' ').toLowerCase();let s=0;photoKey(r).forEach(k=>{if(t.includes(k))s+=3});if(/cocktail|drink|mixed drink|martini|highball|negroni|swizzle|sour|spritz|daiquiri|margarita/i.test(t))s+=3;if(/logo|coat of arms|crest|portrait|building|map|diagram|book cover|fruit illustration/i.test(t))s-=8;return s}
async function exactDbPhoto(r){try{const res=await fetch(`https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${encodeURIComponent(r.name)}`);if(!res.ok)return null;const j=await res.json(),k=normDrink(r.name),d=(j.drinks||[]).find(x=>normDrink(x.strDrink)===k);if(d?.strDrinkThumb)return{url:d.strDrinkThumb,credit:'TheCocktailDB',link:`https://www.thecocktaildb.com/drink/${d.idDrink}`}}catch(e){}return null}
findRemotePhoto=async function(r){let info=await exactDbPhoto(r);if(!info){try{const res=await fetch(`https://api.openverse.org/v1/images/?q=${encodeURIComponent(r.name+' cocktail drink')}&page_size=12`);if(res.ok){const j=await res.json(),rank=(j.results||[]).map(x=>({x,s:photoScore(r,x)})).sort((a,b)=>b.s-a.s),hit=rank.find(z=>z.s>=6)?.x;if(hit)info={url:hit.thumbnail||hit.url,credit:[hit.creator,hit.license?.toUpperCase()].filter(Boolean).join(' · ')||'Openverse',link:hit.foreign_landing_url||hit.detail_url}}}catch(e){}}if(info){state.remotePhotos[r.id]=info;saveRemotePhotos();return info}return null};
fallbackPhoto=function(r){const title=String(r.name||'Cocktail').replace(/[&<>]/g,''),fam=String(r.family||'Cocktail').replace(/[&<>]/g,''),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900" viewBox="0 0 1200 900"><defs><radialGradient id="g"><stop stop-color="#20262e"/><stop offset="1" stop-color="#0e1014"/></radialGradient></defs><rect width="1200" height="900" fill="url(#g)"/><circle cx="600" cy="355" r="150" fill="none" stroke="#c99a50" stroke-width="3" opacity=".55"/><circle cx="600" cy="355" r="108" fill="none" stroke="#c99a50" opacity=".22"/><path d="M535 285h130l-24 205h-82z" fill="#c99a50" opacity=".08" stroke="#c99a50"/><text x="600" y="650" text-anchor="middle" fill="#eee8de" font-family="Georgia,serif" font-size="44">${title}</text><text x="600" y="700" text-anchor="middle" fill="#8c8d90" font-family="Arial,sans-serif" font-size="21">${fam} · photo not verified yet</text></svg>`;return`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`};
loadPhoto=async function(id,img){const r=state.byId.get(id);if(!r||!img)return;const host=img.closest('.card-photo,.detail-photo,.hero-media'),status=host?.querySelector('.photo-status'),mode=state.photoMode[id]||'system',custom=mode==='custom'?await getCustomPhoto(id):null;if(mode==='custom'&&custom){img.onload=()=>status?.remove();img.src=URL.createObjectURL(custom);img.dataset.credit='Your photo';return}let info=null;if(mode==='remote'&&state.remotePhotos[id]?.url)info=state.remotePhotos[id];else if(/^https?:\/\//i.test(String(r.image||'')))info={url:r.image,credit:srcName(r)};else if(state.remotePhotos[id]?.url)info=state.remotePhotos[id];else info=await findRemotePhoto(r);if(!info?.url)info={url:fallbackPhoto(r),credit:'No verified external photo found'};img.onload=()=>status?.remove();img.onerror=()=>{img.onerror=null;img.src=fallbackPhoto(r);if(status)status.textContent='Photo unavailable'};img.src=info.url;img.dataset.credit=info.credit||'';img.dataset.link=info.link||'';const c=img.closest('.detail-photo')?.querySelector('.photo-credit');if(c)c.innerHTML=info.link?`<a href="${attr(info.link)}" target="_blank" rel="noopener">${esc(info.credit||'Image source')}</a>`:esc(info.credit||'')};

const poll=setInterval(()=>{if(state.recipes.length){clearInterval(poll);const s=$('#searchInput');if(s)s.placeholder=`Search ${state.recipes.length}+ cleaned recipes, ingredients, countries...`}},25);setTimeout(()=>clearInterval(poll),10000);
})();
